version: "3.8"
services:
  jolie:
    image: jolielang/jolie:edge-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/workspaces/BachelorCode
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail", "-f", "/dev/null"]

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_HOST_PORT=:14260
      
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - ./loki-data:/tmp/loki

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - jaeger

  # Shared OpenTelemetry collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"  # OTLP gRPC port
      - "4318:4318"  # OTLP HTTP port
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
